### ISSUE TITLE
testing imported in non _test.go file

### ISSUE THREAD

**Issue by whyrusleeping** [jbenet/go-peerstream#8]
in your `transport/test/ttest.go` file you import testing, i'm going through ipfs and its deps and flagging everything that does this.

**Comment by jbenet** [comment]
it's to define a common test suite to be run on multiple transports. is there a better way to do this?

**Comment by whyrusleeping** [comment]
hrm... I'm not sure. the problem is that if this makes it as a dependency into any file using flag, it screws things up.. i guess i can probably be certain that this one wasnt the issue.

**Comment by jbenet** [comment]
understood. yeah it's under `transport/test` to signify it's to be used with testing. happy to use a better way but doesn't seem to be causing the problem atm
